-- Migration: Seed historical_events table with official foundational records
-- Description: Insere 25 eventos históricos reais distribuídos pelas oito Eras do CHRONOS.
-- Sprint: 4.2.2
-- Date: 18/07/2026
-- Author: Equipe de Engenharia CHRONOS

BEGIN;

-- 1. Domínio do Fogo por Hominídeos (Pré-História)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'pre-historia'),
    'dominio-do-fogo',
    'Domínio do Fogo por Hominídeos',
    'Domínio do Fogo',
    E'A habilidade de controlar e reproduzir o fogo permitiu aos primeiros hominídeos, como o Homo erectus, colonizar climas mais frios na Eurásia, melhorar a digestibilidade dos alimentos por meio do cozimento e desenvolver interações sociais mais complexas ao redor de fogueiras.',
    'A domesticação do fogo representou um ponto de virada evolutivo, proporcionando luz, calor, proteção contra predadores e a possibilidade de cozinhar alimentos.',
    'scientific',
    'approximate',
    -1000000,
    NULL,
    -1.292100,
    36.821900,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 2. Revolução Neolítica (Pré-História)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'pre-historia'),
    'revolucao-neolitica',
    'A Revolução Neolítica e Agrícola',
    'Revolução Neolítica',
    E'Iniciada de forma independente em várias partes do globo, notadamente no Crescente Fértil, a Revolução Neolítica transformou a ecologia humana. O cultivo de cereais e a domesticação de animais permitiram excedentes alimentares, o crescimento populacional e o surgimento das primeiras aldeias permanentes.',
    'A transição histórica de sociedades nômades de caçadores-coletores para o sedentarismo agrícola, marcando o início da domesticação de plantas e animais.',
    'social',
    'approximate',
    -10000,
    -4000,
    36.166700,
    43.116700,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 3. Construção da Grande Pirâmide de Gizé (Antiguidade)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade'),
    'construcao-da-grande-piramide-de-gize',
    'Construção da Grande Pirâmide de Gizé',
    'Pirâmide de Gizé',
    E'Erguida no planalto de Gizé durante o Império Antigo egípcio, a estrutura permaneceu como a construção mais alta feita pelo ser humano durante mais de 3.800 anos. Sua edificação exigiu uma complexa organização logística e mobilização de dezenas de milhares de trabalhadores.',
    'O monumental túmulo de pedra construído para o faraó Quéops durante o Império Antigo, representando o auge da engenharia civil clássica e da forte centralização de poder do Egito Antigo.',
    'cultural',
    'approximate',
    -2560,
    -2540,
    29.979200,
    31.134200,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 4. Código de Hamurábi (Antiguidade)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade'),
    'codigo-de-hamurabi',
    'Promulgação do Código de Hamurábi',
    'Código de Hamurábi',
    E'Esculpido em uma estela de diorito preto, o código consiste em 282 leis que regulavam a vida civil, comercial e penal na antiga Mesopotâmia. Ele consolidou o papel do monarca como distribuidor da justiça divina e estabeleceu punições baseadas no status social dos indivíduos envolvidos.',
    'Um dos conjuntos de leis escritas mais antigos e completos do mundo antigo, estabelecido pelo rei babilônico Hamurábi e célebre pela rigorosa aplicação da Lei de Talião.',
    'political',
    'approximate',
    -1750,
    NULL,
    32.536400,
    44.420800,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 5. Invenção do Alfabeto Fenício (Antiguidade)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade'),
    'invencao-do-alfabeto-fenicio',
    'Desenvolvimento do Alfabeto Fonético Fenício',
    'Alfabeto Fenício',
    E'Diferente dos sistemas cuneiformes ou hieróglifos, que exigiam centenas de símbolos, o alfabeto fenício associou caracteres a fonemas simples. Propagado por rotas marítimas mediterrâneas, influenciou o desenvolvimento do alfabeto grego, aramaico, latino e cirílico.',
    'O desenvolvimento de um sistema inovador de escrita simplificado contendo 22 caracteres consonantais que revolucionou o comércio mediterrâneo e serviu de base para quase todos os alfabetos modernos.',
    'cultural',
    'approximate',
    -1050,
    NULL,
    33.884900,
    35.495100,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 6. Fundação da República Romana (Antiguidade Clássica)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade-classica'),
    'fundacao-da-republica-romana',
    'Fundação da República Romana',
    'República Romana',
    E'Com a derrubada de Tarquínio, o Soberbo, a aristocracia romana substituiu a monarquia por uma república liderada por dois cônsules. Essa mudança deu início a séculos de expansão militar, luta patrícia-plebeia e ao desenvolvimento do renomado Direito Romano.',
    'A queda da monarquia através da deposição do último rei etrusco de Roma, dando lugar ao estabelecimento de um sistema republicano inédito de governo liderado pelo Senado e por cônsules eleitos.',
    'political',
    'exact',
    -509,
    NULL,
    41.890200,
    12.492200,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 7. Batalha de Maratona (Antiguidade Clássica)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade-classica'),
    'batalha-de-maratona',
    'A Batalha de Maratona nas Guerras Médicas',
    'Batalha de Maratona',
    E'Ocorrida na planície de Maratona, a vitória militar grega demonstrou a eficácia da tática de falange dos hoplitas contra as forças do Império Aquemênida. O evento tornou-se símbolo de liberdade civil e deu origem à famosa lenda da corrida do mensageiro até Atenas.',
    'O confronto histórico no qual os cidadãos atenienses repeliram a primeira invasão persa comandada por Dario I, preservando a autonomia das cidades-estado gregas.',
    'military',
    'exact',
    -490,
    NULL,
    38.153400,
    23.978200,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 8. Inauguração do Coliseu (Antiguidade Clássica)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade-classica'),
    'inauguracao-do-coliseu',
    'Inauguração do Anfiteatro Flaviano em Roma',
    'Inauguração do Coliseu',
    E'Conhecido originalmente como Anfiteatro Flaviano, o Coliseu foi iniciado por Vespasiano e concluído por seu filho Tito. A arena abrigava espetáculos de gladiadores, encenações de batalhas navais e caças de animais selvagens, funcionando como instrumento de propaganda estatal.',
    'Os monumentais espetáculos e jogos de inauguração do Anfiteatro Flaviano erguido em Roma pelos imperadores da dinastia Flaviana, marcando de forma definitiva a arquitetura pública imperial de Roma.',
    'cultural',
    'exact',
    80,
    NULL,
    41.890200,
    12.492200,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 9. Queda do Império Romano do Ocidente (Antiguidade Clássica)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'antiguidade-classica'),
    'queda-do-imperio-romano-do-ocidente',
    'Deposição de Rômulo Augusto e Queda de Roma',
    'Queda de Roma',
    E'Enfraquecido por crises econômicas, corrupção interna, divisões políticas e invasões bárbaras sucessivas, o Império Romano do Ocidente ruiu em 476 d.C. O evento simboliza o colapso da autoridade centralizada na Europa Ocidental e a fragmentação em reinos germânicos.',
    'A destituição formal do último imperador romano do ocidente, Rômulo Augusto, pelo chefe mercenário germânico Odoacro, marcando de forma emblemática o colapso de Roma e a transição definitiva para a Idade Média.',
    'political',
    'exact',
    476,
    NULL,
    41.890200,
    12.492200,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 10. Tratado de Verdun (Idade Média)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-media'),
    'tratado-de-verdun',
    'Assinatura do Tratado de Verdun',
    'Tratado de Verdun',
    E'Assinado em agosto de 843, o tratado dividiu o império em Francia Ocidental, Francia Oriental e Francia Média. Esse evento descentralizou o poder e estabeleceu as bases geopolíticas fundamentais para a formação posterior das nações da França e da Alemanha.',
    'O acordo que dividiu o vasto Império Carolíngio entre os três netos sobreviventes de Carlos Magno, delineando as fronteiras futuras da Europa ocidental.',
    'political',
    'exact',
    843,
    NULL,
    49.160100,
    5.381200,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 11. Primeira Cruzada (Idade Média)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-media'),
    'primeira-cruzada',
    'Convocação e Campanha da Primeira Cruzada',
    'Primeira Cruzada',
    E'Após o apelo do imperador bizantino Aleixo I, a cruzada mobilizou milhares de cavaleiros, nobres e camponeses europeus. O conflito culminou no cerco e na captura de Jerusalém em 1099, estabelecendo vários Estados Cruzados na região do Levante.',
    'A ampla campanha militar e religiosa convocada de forma fervorosa pelo Papa Urbano II no Concílio de Clermont, visando retomar o controle de Jerusalém e de outros locais sagrados da Terra Santa.',
    'religious',
    'year',
    1095,
    1099,
    31.768300,
    35.213700,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 12. Assinatura da Magna Carta (Idade Média)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-media'),
    'assinatura-da-magna-carta',
    'Outorga da Magna Carta na Inglaterra',
    'Magna Carta',
    E'Redigida para restaurar a paz civil, a carta garantiu direitos feudais, protegeu os barões de impostos ilegais e estabeleceu o princípio de que o próprio rei estava sujeito à lei, lançando as bases iniciais para o desenvolvimento constitucional moderno.',
    'O documento assinado pelo rei João Sem-Terra sob pressão de barões rebeldes, limitando pela primeira vez a autoridade monárquica absoluta na Inglaterra.',
    'political',
    'exact',
    1215,
    NULL,
    51.444200,
    -0.565100,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 13. Invenção da Imprensa de Tipos Móveis (Renascimento)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'renascimento'),
    'invencao-do-banco-de-dados-tipos-moveis', -- slug único adaptado
    'Desenvolvimento da Imprensa por Johannes Gutenberg',
    'Imprensa de Gutenberg',
    E'Ao combinar tintas à base de óleo, moldes metálicos de precisão e prensas de madeira adaptadas de prensas de uva, Gutenberg viabilizou a impressão em massa de livros. O avanço acelerou a disseminação de ideias científicas, humanistas e religiosas.',
    'A revolucionária criação da tecnologia de prensa móvel mecânica tipográfica na Alemanha, acelerando de forma exponencial a difusão rápida de livros, ideias e o nível de alfabetização na Europa Ocidental.',
    'scientific',
    'approximate',
    1440,
    NULL,
    49.992900,
    8.247300,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 14. Queda de Constantinopla (Idade Média)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-media'),
    'queda-de-constantinopla',
    'O Cerco e Queda de Constantinopla',
    'Queda de Constantinopla',
    E'Após um cerco de 53 dias que envolveu o uso inovador de artilharia pesada de canhões, as forças otomanas romperam as muralhas bizantinas. O evento provocou o fechamento de rotas comerciais terrestres para a Ásia, estimulando as navegações europeias.',
    'A conquista militar e captura da imponente capital bizantina pelas forças do jovem Império Otomano sob o comando do sultão Maomé II, pondo um fim definitivo ao milenar Império Romano do Oriente.',
    'military',
    'exact',
    1453,
    NULL,
    41.008200,
    28.978400,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 15. Descoberta da América (Idade Moderna)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-moderna'),
    'descoberta-da-america',
    'A Viagem de Cristóvão Colombo e a Chegada à América',
    'Viagem de Colombo',
    E'Financiada pelos Reis Católicos da Espanha, a travessia atlântica das caravelas Santa María, Pinta e Niña visava uma rota ocidental rumo às Índias. O contato estabelecido reconfigurou irreversivelmente a geopolítica, economia e demografia globais.',
    'A expedição espanhola sob comando do navegador Cristóvão Colombo que atingiu as ilhas do Caribe, iniciando o processo duradouro de integração econômica, cultural e demográfica entre o Velho Mundo e o continente americano.',
    'other',
    'exact',
    1492,
    NULL,
    24.000000,
    -74.500000,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 16. Pintura do Teto da Capela Sistina (Renascimento)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'renascimento'),
    'pintura-do-teto-da-capela-sistina',
    'Pintura do Teto da Capela Sistina por Michelangelo',
    'Capela Sistina',
    E'Executada ao longo de quatro anos de trabalho árduo sob andaimes, a pintura exibe composições anatômicas dramáticas de extremo vigor realista, incluindo a icônica cena de "A Criação de Adão". É considerada um marco insuperável da arte renascentista.',
    'A grandiosa e célebre obra artística em afresco pintada pelo mestre renascentista Michelangelo Buonarroti sob encomenda do Papa Júlio II, representando com extremo realismo anatômico nove passagens do Livro do Gênesis.',
    'cultural',
    'year',
    1508,
    1512,
    41.903000,
    12.454500,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 17. Publicação das 95 Teses (Idade Moderna)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-moderna'),
    'publicacao-das-95-teses',
    'Fixação das 95 Teses de Martinho Lutero',
    '95 Teses de Lutero',
    E'Ao afixar suas teses na porta da Igreja do Castelo de Wittenberg, o monge Martinho Lutero buscou abrir um debate acadêmico. O ato gerou uma ruptura profunda na unidade do cristianismo europeu, enfraquecendo o poder pontifício e reestruturando a sociedade.',
    'A histórica publicação do conjunto de teses teológicas críticas ao poder papal e à exploração comercial de indulgências em Wittenberg, desencadeando a cisão religiosa conhecida como Reforma Protestante.',
    'religious',
    'exact',
    1517,
    NULL,
    51.866700,
    12.643100,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 18. Publicação da Teoria Heliocêntrica (Renascimento)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'renascimento'),
    'publicacao-da-teoria-heliocentrica',
    'Publicação do De Revolutionibus por Nicolau Copérnico',
    'Teoria Heliocêntrica',
    E'Publicada no ano da morte de Nicolau Copérnico, a obra "De revolutionibus orbium coelestium" usou modelos matemáticos refinados para demonstrar que a Terra e outros planetas orbitam ao redor do Sol, iniciando a Revolução Científica moderna.',
    'A publicação da célebre obra astronômica de Nicolau Copérnico que apresentou o modelo heliocêntrico, posicionando formalmente o Sol como o centro orbital do sistema e contestando a doutrina clássica de Ptolomeu.',
    'scientific',
    'exact',
    1543,
    NULL,
    54.035400,
    19.027200,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 19. Fundação da Royal Society (Idade Moderna)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-moderna'),
    'fundacao-da-royal-society',
    'Fundação da Royal Society de Londres',
    'Royal Society',
    E'Fundada sob o lema "Nullius in verba" (Na palavra de ninguém), a Royal Society de Londres promoveu o método experimental baconiano. Congreou pensadores fundamentais como Robert Boyle, Isaac Newton e Hooke, legitimando a ciência como esforço coletivo.',
    'A criação oficial da primeira academia nacional de ciências em Londres sob o lema de validação empírica, estruturando a pesquisa científica coletiva e a publicação de descobertas experimentais na Europa moderna.',
    'scientific',
    'exact',
    1660,
    NULL,
    51.503300,
    -0.127600,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 20. Patente da Máquina a Vapor de Watt (Revolução Industrial)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'revolucao-industrial'),
    'patente-da-maquina-a-vapor-de-watt',
    'Registro da Patente do Condensador Separado de James Watt',
    'Máquina a Vapor de Watt',
    E'Ao impedir o resfriamento contínuo do cilindro principal, a inovação de Watt reduziu em até 75% o consumo de carvão se comparada ao motor Newcomen pré-existente. A máquina tornou-se a força motriz essencial para fábricas de fiação e ferrovias.',
    'A histórica patente do condensador separado obtida pelo inventor escocês James Watt, que reduziu o consumo de carvão em mais de 70% e forneceu a fonte de energia mecânica eficiente indispensável para a expansão industrial.',
    'scientific',
    'exact',
    1769,
    NULL,
    55.864200,
    -4.251800,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 21. Queda da Bastilha (Idade Contemporânea)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-contemporanea'),
    'queda-da-bastilha',
    'Tomada da Bastilha e Início da Revolução Francesa',
    'Queda da Bastilha',
    E'Em 14 de julho de 1789, a população parisiense armada tomou a Bastilha em busca de pólvora. O evento precipitou o colapso do Antigo Regime absolutista francês e impulsionou a aprovação da Declaração dos Direitos do Homem e do Cidadão.',
    'O assalto popular à prisão-fortaleza de Paris que simbolizava a opressão e o absolutismo real Bourbon, desencadeando as reformas radicais republicanas.',
    'political',
    'exact',
    1789,
    NULL,
    48.853100,
    2.369100,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 22. Inauguração da Linha Ferroviária de Liverpool a Manchester (Revolução Industrial)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'revolucao-industrial'),
    'linha-ferroviaria-liverpool-manchester',
    'Abertura da Ferrovia Liverpool e Manchester',
    'Ferrovia Liverpool-Manchester',
    E'Projetada por George Stephenson, a ferrovia provou a viabilidade comercial dos trilhos a vapor de alta velocidade no transporte de mercadorias entre o porto de Liverpool e as tecelagens de Manchester, acelerando significativamente a integração industrial britânica.',
    'A inauguração oficial da primeira linha ferroviária de transporte regular de passageiros e cargas totalmente operada por locomotivas a vapor de alta velocidade, integrando o porto de Liverpool ao centro fabril de Manchester.',
    'economic',
    'exact',
    1830,
    NULL,
    53.408400,
    -2.991600,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 23. Primeira Linha de Telégrafo Elétrico Comercial (Revolução Industrial)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'revolucao-industrial'),
    'primeiro-telegrafo-eletrico-comercial',
    'Instalação do Telégrafo de Cooke e Wheatstone',
    'Telégrafo de Cooke-Wheatstone',
    E'Desenvolvido por William Fothergill Cooke e Charles Wheatstone, o sistema permitiu a transmissão quase instantânea de mensagens de segurança ferroviária e comerciais. Foi o primeiro passo para a conectividade global de telecomunicações de longo alcance.',
    'A pioneira entrada em operação comercial do primeiro sistema prático de telégrafo elétrico, instalado ao longo da linha ferroviária Great Western Railway, inaugurando a era das telecomunicações eletrônicas globais instantâneas.',
    'scientific',
    'exact',
    1837,
    NULL,
    51.517400,
    -0.121400,
    4,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 24. Início da Primeira Guerra Mundial (Idade Contemporânea)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-contemporanea'),
    'inicio-da-primeira-guerra-mundial',
    'Eclosão da Primeira Guerra Mundial',
    'Primeira Guerra Mundial',
    E'O assassinato desencadeou uma crise diplomática europeia que ativou uma complexa rede de alianças secretas entre potências. O conflito mobilizou dezenas de milhões de combatentes e reconfigurou radicalmente as fronteiras do continente europeu.',
    'A eclosão oficial do devastador conflito militar global após o assassinato do herdeiro austro-húngaro Francisco Fernando em Sarajevo, desencadeando a imediata mobilização em massa de alianças militares europeias rivais.',
    'military',
    'exact',
    1914,
    1918,
    43.856300,
    18.413100,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

-- 25. Lançamento do Apollo 11 (Idade Contemporânea)
INSERT INTO historical_events (
    era_id,
    slug,
    titulo,
    titulo_curto,
    descricao,
    descricao_resumida,
    event_type,
    date_precision,
    start_year,
    end_year,
    latitude,
    longitude,
    importance_score,
    publication_status,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM eras WHERE slug = 'idade-contemporanea'),
    'lancamento-do-apollo-11',
    'A Missão Apollo 11 e o Primeiro Pouso na Lua',
    'Apollo 11',
    E'Lançada pelo gigantesco foguete Saturno V em 16 de julho, a missão levou os astronautas Neil Armstrong, Buzz Aldrin e Michael Collins à Lua. No dia 20 de julho, o módulo de pouso Eagle tocou o solo do satélite, selando o auge da Corrida Espacial.',
    'O lançamento da ambiciosa missão espacial tripulada da NASA que alcançou o sucesso histórico de pousar o módulo lunar Eagle no Mar da Tranquilidade, permitindo que os primeiros seres humanos caminhassem em solo lunar.',
    'scientific',
    'exact',
    1969,
    NULL,
    28.572100,
    -80.648000,
    5,
    'published',
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    era_id = EXCLUDED.era_id,
    titulo = EXCLUDED.titulo,
    titulo_curto = EXCLUDED.titulo_curto,
    descricao = EXCLUDED.descricao,
    descricao_resumida = EXCLUDED.descricao_resumida,
    event_type = EXCLUDED.event_type,
    date_precision = EXCLUDED.date_precision,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    importance_score = EXCLUDED.importance_score,
    publication_status = EXCLUDED.publication_status,
    ativo = EXCLUDED.ativo,
    updated_at = NOW();

COMMIT;
